# Generated by Django 5.2.4 on 2025-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='weight',
            field=models.FloatField(default=100),
        ),
    ]
