# Generated by Django 5.2.4 on 2025-07-29 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_foodcategory_food_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Зріст (см)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вага (кг)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Фото профілю')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('other', 'Інше')], max_length=10, null=True, verbose_name='Стать')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Сидячий (мало або без фізичної активності)'), ('light', 'Легка активність (1-3 дні на тиждень)'), ('moderate', 'Помірна активність (3-5 днів на тиждень)'), ('active', 'Висока активність (6-7 днів на тиждень)'), ('very_active', 'Дуже висока активність (щоденні інтенсивні тренування)')], default='sedentary', max_length=20, verbose_name='Рівень активності')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
