# Generated by Django 5.2.4 on 2025-07-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile.png', null=True, upload_to='profile_pics/', verbose_name='Фото профілю'),
        ),
    ]
