# Generated by Django 5.2.4 on 2025-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Наприклад: горіхи, лактоза, глютен', verbose_name='Алергії (перелічіть через кому)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Бажана вага (кг)'),
        ),
    ]
